### ISSUE TITLE
Se pide un departamento al crear tarea cuando no es obligatorio poner uno en el proyecto

### ISSUE THREAD

**Issue by fanyCaz** [GerFl/WorkFlow#8]
Al crear un proyecto, no es obligatorio poner departamentos, sin embargo, lo pide como requisito para agregar una tarea.
![image](https://user-images.githubusercontent.com/48691409/129429896-97b815df-aed4-40b1-aa2b-51c2c977cb2f.png)

**Comment by GerFl** [comment]
New bug: Al crear una tarea sin departamento, la función de conteo en el script se crashea.
